#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Local test DB (ART-4 / PRODUCTION_READINESS D1-D2).
#
# Boots the LOCAL Supabase stack, applies migrations 0001..0012 + the synthetic
# staging seed, and writes apps/platform/.env.local so the DB-backed vitest suite
# connects to the local stack. NEVER touches the connected cloud project. Requires
# Docker running. Idempotent: safe to re-run (db reset gives a clean DB each time).
#
#   bash scripts/test-db.sh            # start + reset + write .env.local
#   npm run test:platform              # then run the DB-backed tests
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/.."

SUPABASE="./node_modules/.bin/supabase"
[ -x "$SUPABASE" ] || SUPABASE="supabase"

echo "==> [1/3] starting local Supabase (idempotent; first run pulls images)…"
"$SUPABASE" start || true   # tolerate "already running"

echo "==> [2/3] db reset: re-apply migrations + seed_staging.sql on a clean DB…"
"$SUPABASE" db reset

echo "==> [3/3] writing apps/platform/.env.local from the local stack status…"
ENV_OUT="$("$SUPABASE" status -o env)"   # emits KEY="value" lines
get() { printf '%s\n' "$ENV_OUT" | sed -n "s/^$1=\"\(.*\)\"$/\1/p"; }
API_URL="$(get API_URL)"
PUBLISHABLE_KEY="$(get PUBLISHABLE_KEY)"   # new-style sb_publishable_… (matches the cloud var)
SECRET_KEY="$(get SECRET_KEY)"             # new-style sb_secret_… (service-role equivalent)

if [ -z "$API_URL" ] || [ -z "$PUBLISHABLE_KEY" ]; then
  echo "ERROR: could not read API_URL/PUBLISHABLE_KEY from 'supabase status -o env'." >&2
  printf '%s\n' "$ENV_OUT" >&2
  exit 1
fi

cat > apps/platform/.env.local <<EOF
# GENERATED by scripts/test-db.sh — LOCAL Supabase stack ONLY. Gitignored; do not commit.
NEXT_PUBLIC_APP_URL=http://localhost:3001
EMAIL_TOKEN_SECRET=local-dev-only-not-a-real-secret
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$PUBLISHABLE_KEY
SUPABASE_SERVICE_ROLE_KEY=$SECRET_KEY
EOF

echo "==> done. local API: $API_URL"
echo "    DB-backed tests:  npm run test:platform"
echo "    stop the stack:   npm run db:stop"
